### ISSUE TITLE
adding team members to org teams

### ISSUE THREAD

**Issue by dibenzepin** [hngx-org/teams#44]
@hngx-org/team-leads i've given yall owner perms for 24 hours (see how you can easily tag en entire group of people?)

you may:

- add people to the org AND ONLY your team
- make sub-teams of your own team

don't go crazy or add anyone else, your actions are being recorded, yadda yadda yadda

what you do afterwards, is up to you...give everyone admin access to your repos, stick with fork-and-branch, idc

sha try and submit your app on time

**Comment by Tomilola-ng** [comment]
## My Team lead is DenScholar from Team-Panther. I need to be added to the Backend lunch repo

### Important

**Comment by poopsicles** [comment]
@Tomilola-ng i texted your lead for you, they'll handle the rest

**Comment by Tomilola-ng** [comment]
Thanks @poopsicles 😊
